-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnPQqR5+5EqgmsGA/
nGnwa7X7O8qIRaFe3C8XkeoE6XygCgYIKoZIzj0DAQehRANCAARTGWFMOqMG7vhR
/hvrWnzRBADnjfwOB5rvqvsQs3BM+XUxbCcimKbUMOkITsTA2KguTa0N4alpRkie
zBsC3IIs
-----END PRIVATE KEY-----